trigger:
- master

pool:
  name: 'Default'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'aks-acr'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aksdepl-rg'
    azureResourceGroup: 'aksdepl'
    kubernetesCluster: 'aks'
    command: 'apply'
    arguments: '-f deploy.yaml'
