apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: aksregdj.azurecr.io/nginx-echo-headers:latest
  imagePullSecrets:
  - name: regcred
